# app/config/security.yml
security:
    # Configurando las listas de control de acceso: mecanismo de seguridad más granular disponible en Symfony2.
    # Una ACL permite asignar permisos específicos a cada objeto y para cada usuario de la aplicación.
    acl:
        connection: default

    #firewall es el mecanismo con el que se protegen las diferentes partes de un sitio web
    firewalls:
        backend:
            pattern: ^/backend
            provider: superadmins
            http_basic: ~

    access_control:
        - { path: ^/backend/*, roles: ROLE_SUPERADMIN }

    providers:
        superadmins:
            memory:
                users:
                    superadmin: {password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_SUPERADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: sha512
