<?php
/**
 * Created by PhpStorm.
 * User: Ramon
 * Date: 18/04/2015
 * Time: 18:32
 */

namespace LRN\LRNProtectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConceptosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosRepository extends EntityRepository
{
    public function FindConcepto($concepto)
    {
        $em=$this->getEntityManager();
        $dql='SELECT e FROM LRNProtectBundle:Conceptos e WHERE e.subtitulo= :concepto';
        $query=$em->createQuery($dql);
        $query->setParameter('concepto',$concepto);
        $entity=$query->getResult();
        return $entity;
    }

    public function FindAllConceptos()
    {
        $em=$this->getEntityManager();
        $dql='SELECT e FROM LRNProtectBundle:Conceptos e ORDER BY e.subtitulo ASC ';
        $query=$em->createQuery($dql);
        $entity=$query->getResult();
        return $entity;
    }
}