<?php

namespace LRN\LRNProtectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentosRepository extends EntityRepository
{
    public function FindAllDocumentos()
    {
        $em=$this->getEntityManager();
        $dql='SELECT d FROM LRNProtectBundle:Documentos d ORDER BY d.temaRelacionado ASC ';
        $query=$em->createQuery($dql);
        $entity=$query->getResult();
        return $entity;
    }

    public function FindAllCat()
    {
        $em=$this->getEntityManager();
        $dql='SELECT DISTINCT d.temaRelacionado FROM LRNProtectBundle:Documentos d ORDER BY d.temaRelacionado ASC ';
        $query=$em->createQuery($dql);
        $entity=$query->getResult();
        return $entity;
    }

    public function FindCat($categoria)
    {
        $em=$this->getEntityManager();
        $dql='SELECT d FROM LRNProtectBundle:Documentos d WHERE d.temaRelacionado= :cat';
        $query=$em->createQuery($dql);
        $query->setParameter('cat',$categoria);
        $entity=$query->getResult();
        return $entity;
    }
}
