<?php

namespace LRN\LRNProtectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasoRepository extends EntityRepository
{

}
