<?php
/**
 * Created by PhpStorm.
 * User: Ramon
 * Date: 26/04/2015
 * Time: 0:41
 */

namespace LRN\LRNProtectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends EntityRepository
{

}
